import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import {Provider} from '../components/ui/provider'
import dynamic from "next/dynamic";
import "stream-chat-react/dist/css/v2/index.css";


const  AuthContextProvider= dynamic(
  () => import("../context/authContext"),
);
const  Navbar = dynamic(
  () => import("../components/custom/Navbar"),
 
);
const   TopNavbar = dynamic(
  () => import("../components/custom/TopNavbar"),

);
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-Inter",
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
      ><AuthContextProvider>
            <Provider>
                <TopNavbar/>
                <Navbar name={null} image={null} islogged={false}/>
                {children}
              </Provider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
