export const angola= [
  { value: "Bengo", label: "Bengo" },
  { value: "Benguela", label: "Benguela" },
  { value: "Bié", label: "Bié" },
  { value: "Cabinda", label: "Cabinda" },
  { value: "Cuando", label: "Cuando" },
  { value: "Cubango", label: "Cubango" },
  { value: "Cuanza Norte", label: "Cuanza Norte" },
  { value: "Cuanza Sul", label: "Cuanza Sul" },
  { value: "Cunene", label: "Cunene" },
  { value: "Huambo", label: "Huambo" },
  { value: "Huíla", label: "Huíla" },
  { value: "Icolo e Bengo", label: "Icolo e Bengo" },
  { value: "Luanda", label: "Luanda" },
  { value: "Lunda Norte", label: "Lunda Norte" },
  { value: "Lunda Sul", label: "Lunda Sul" },
  { value: "Malanje", label: "Malanje" },
  { value: "Moxico", label: "Moxico" },
  { value: "Moxico Leste", label: "Moxico Leste" },
  { value: "Namibe", label: "Namibe" },
  { value: "Uíge", label: "Uíge" },
  { value: "Zaire", label: "Zaire" }
]

export const municipos_angola = [
  {
    province: "Bengo",
    municipalities: [
      "Ambriz",
      "Bula Atumba",
      "Dande",
      "Dembos",
      "Nambuangongo",
      "Pango Aluquém"
    ],
    municipio:[{nome:"Ambriz",comunas:["Bela Vista", "Ambriz", "Tabi"]},
    {nome:'Bula Atumba', comunas:["Bula Atumba", "Quiage"]},{nome:"Dande", comunas:["Barra do Dande", "Caxito", "Mabubas", "Quicabo", "Úcua"]},
    {nome:"Dembos", comunas:["Quibaxe", "Piri", "Paredes", "Coxe"]},
    {nome:"Nambuangongo", comunas:["Canacassala", "Quicunzo", "Muxaluando", "Gombe", "Cage", "Zala"]},
    {nome:"Pango Aluquém", comunas:["Pango Aluquém", "Cazuangongo"]},
]
  },
  {
    province: "Benguela",
    municipalities: [
      "Balombo",
      "Baía Farta",
      "Benguela",
      "Bocoio",
      "Caimbambo",
      "Catumbela",
      "Chongorói",
      "Cubal",
      "Ganda",
      "Lobito"
    ],
    municipio:[{nome:"Baia Farta" , comunas:["Dombe Grande", "Baía Farta", "Calohanga", "Equimina"]},
    {nome:"Balombo" , comunas:["Balombo", "Chingongo", "Chindumbo", "Maca Mombolo"]},
    {nome:"Benguela" , comunas:['']},
    {nome:"Bocoio" , comunas:["Bocoio", "Cubal do Lumbo", "Monte Belo", "Chila", "Passe"]},
    {nome:"Caimbambo" , comunas:["Caimbambo", "Catengue", "Caiave", "Canhamela", "Viangombe"]},
    {nome:"Catumbela" , comunas:["Catumbela", "Biópio", "Gama", "Praia", "Bebé"]},
    {nome:"Chongorói" , comunas:["Chongorói", "Bolonguera", "Camuine"]},
    {nome:"Cubal" , comunas:["Capupa"," Cubal", "Tumbulo", "Iambala"]},
    {nome:"Ganda" , comunas:["Ganda"," Ebanga", "Chicuma", "Babaera", "Casseque"]},
    {nome:"Lobito" , comunas:["Egito Praia", "Lobito", "Canata", "Canjala"]},
]
  },
  {
    province: "Bié",
    municipalities: [
      "Andulo",
      "Camacupa",
      "Catabola",
      "Chinguar",
      "Chitembo",
      "Cuemba",
      "Cunhinga",
      "Cuíto",
      "Nharea"
    ],
    municipio:[{nome:"Andulo", comunas:["Andulo", "Calucinga", "Cassumbe", "Chivaúlo"]},
    {nome:"Camacupa", comunas:["Ringoma", "Camacupa", "Muinha", "Umpulo", "Cuanza"]},
    {nome:"Catabola", comunas:["Catabola", "Chipeta", "Caiuera", "Chiuca", "Sande"]},
    {nome:"Chinguar", comunas:["Chinguar", "Cutato", "Cangote"]},
    {nome:"Chitembo", comunas:["Cachingues", "Chitembo", "Mutumbo"," Mumbué", "Malengue", "Soma Cuanza"]},
    {nome:"Cuemba", comunas:["Luando", "Munhango", "Cuemba", "Sachinemuna"]},
    {nome:"Cunhinga", comunas:["Cunhinga", "Belo Horizonte"]},
    {nome:"Cuíto", comunas:["Cuito", "Chicala", "Cunje", "Trumba", "Cambândua"]},
    {nome:"Nharea", comunas:["Nharêa", "Gamba", "Lúbia", "Caiei", "Dando"]},
]
  },
  {
    province: "Cabinda",
    municipalities: [
      "Belize",
      "Buco-Zau",
      "Cabinda",
      "Cacongo",
      "Miconje",
      "Massabi",
      "Necuto",
      "Tando Zinze",
      "Liambo",
      "Ngoio"
    ],
    municipio:[{nome:"Belize", comunas:["Luali", "Belize"]},
            {nome:"Buco-Zau", comunas:[""]},
            {nome:"Cabinda", comunas:[""]},
            {nome:"Cacongo", comunas:["Dinge", "Lândana"]},
            {nome:"Miconje", comunas:[""]},
            {nome:"Massabi", comunas:[""]},
            {nome:"Necuto", comunas:["Necuto", "Inhuca"]},
            {nome:"Tando Zinze", comunas:["Tando Zinze", "Malembo"]},
            {nome:"Liambo", comunas:[""]},
            {nome:"Ngoio", comunas:[""]}
]
  },
  {
    province: "Cuanza Norte",
    municipalities: [
      "Ambaca",
      "Banga",
      "Bolongongo",
      "Cambambe",
      "Cazengo",
      "Golungo Alto",
      "Lucala",
      "Ngonguembo",
      "Quiculungo",
      "Samba Cajú"
    ],
     municipio:[{nome:"Ambaca",comunas:["Camabatela", "Tango"," Máua", "Bindo"," Luinga"]},
            {nome:"Banga",comunas:["Banga", "Caculo Cabaça", "Aldeia Nova", "Cariamba"]},
            {nome:"Bolongongo",comunas:["Bolongongo", "Terreiro", "Quiquiemba"]},
            {nome:"Cambambe",comunas:["Dondo, Massangano", "Dange ya Menha"," Zenza do Itombe", "São Pedro da Quilemba"]},
            {nome: "Cazengo",comunas:["Ndalatando", "Canhoca"]},
            {nome:"Golungo Alto",comunas:["Golungo Alto", "Cambondo", "Cêrca", "Quiluanje"]},
            {nome:"Lucala",comunas:["Lucala Quiangombe"]},
            {nome:"Ngonguembo",comunas:["Quilombo dos Dembos"," Camame", "Cavunga"]},
            {nome:"Quiculungo",comunas:["Quiculungo"]},
            {nome:"Samba Cajú",comunas:["Quiculungo"]}]
  },
  {
    province: "Cuanza Sul",
    municipalities: [
      "Gabela",
      "Cassongue",
      "Cela",
      "Conda",
      "Ebo",
      "Libolo",
      "Mussende",
      "Porto Amboim",
      "Quibala",
      "Quilenda",
      "Seles",
      "Sumbe"
    ],
     municipio:[{nome:'Gabela', comunas:["Gabela", "Assango"]},
            {nome:'Cassongue', comunas:["Cassongue", "Pambangala", "Dumbi", "Atóme"]},
            {nome:'Cela', comunas:["Sanga", "Waku Kungo", "Quissanga Cunjo"]},
            {nome:'Conda', comunas:["Conda", "Cunjo"]},
            {nome:'Ebo', comunas:["Ebo", "Condé", "Quissanje"]},
            {nome:'Libolo', comunas:["Calulo", "Munenga", "Cabuta", "Quissongo"]},
            {nome:'Mussende', comunas:["Mussende", "Quienha", "São Lucas"]},
            {nome:'Porto Amboim', comunas:["Capolo", "Porto Amboim"]},
            {nome:'Quibala', comunas:["Quilenda", "Quirimbo"]},
            {nome:'Quilenda', comunas:["Quibala", "Dala Cachibo", "Cariango"," Lonhe"]},
            {nome:'Seles', comunas:["Seles", "Amboiva"," Botera"]},
            {nome:'Sumbe', comunas:["Sumbe", "Gungo", "Gangula", "Quicombo"]}
]
  },
  {
    province: "Cunene",
    municipalities: [
      "Cahama",
      "Cuanhama",
      "Curoca",
      "Cuvelai",
      "Namacunde",
      "Ombadja",
      "CHIÉDE",
      "NEHONE",
      "Humbe",
      "MUPA",
      "NAULILA",
      "CHITADO",
      "CAFIMA",
      "CHISSUATA"
      
    ],
     municipio:[{nome:"Cahama", comunas:["Cahama", "Otchinjau"]},
            {nome:"Cuanhama", comunas:["Ondjiva", "Môngua"]},
            {nome:"Curoca", comunas:[""]},
            {nome:"Cuvelai", comunas:['']},
            {nome:"Namacunde", comunas:[""]},
            {nome:"Ombadja", comunas:["Xangongo", "Ombala yo Mungu"]},
            {nome:"CHIÉDE", comunas:[""]},
            {nome:"NEHONE", comunas:["Nehone", 'Evale']},
            {nome:'Humbe', comunas:["Mucope", "Humbe"]},
            {nome:'Mupa', comunas:[""]},
            {nome:"NAULILA", comunas:[""]},
            {nome:"CHITADO", comunas:[""]},
            {nome:"CAFIMA", comunas:[""]},
            {nome:"CHISSUATA", comunas:[""]}]
  },
  {
    province: "Huambo",
    municipalities: [
      "Bailundo",
      "Caála",
      "Catchiungo",
      "Chicala-Cholohanga",
      "Chinjenje",
      "Ecunha",
      "Huambo",
      "Londuimbali",
      "Longonjo",
      "Mungo",
      "Ukuma",
      "Bimbe", 
      "Sambo",
      "Galanga",
      "Alto Hama",
      "Chilata",
      "Cuima"
    ],
     municipio:[{nome:"Bailundo", comunas:["Bailundo", 'Lunge', "Luvemba"]},
            {nome:"Caála", comunas:[""]},
            {nome:"Catchiungo", comunas:["Chinhama", "Cachiungo"]},
            {nome:"Chicala-Cholohanga", comunas:["Mbave", "Chicala"]},
            {nome:"Chinjenje", comunas:["Chinjenje", "Chiaca"]},
            {nome:"Ecunha", comunas:["Ecunha", "Quipeio"]},
            {nome:"Huambo", comunas:["Huambo"," Calima"]},
            {nome:"Londuimbali", comunas:["Londuimbali", "Ussoque"]},
            {nome:"Longonjo", comunas:["Longonjo", "Lépi"]},
            {nome:"Mungo", comunas:["Mungo", "Cambuengo"]},
            {nome:"Ukuma", comunas:["Ucuma", "Cacoma", "Mundundo"]},
            {nome:"Bimbe", comunas:["Bimbe", "Hengue"]},
            {nome:"Sambo", comunas:["Sambo", "Samboto"]},
            {nome:"Galanga", comunas:["Galanga", "Cumbira"]},
            {nome:"Alto Hama", comunas:[""]},
            {nome:"Chilata", comunas:[""]},
            {nome:"Cuima", comunas:["Cuima", "Catata"]}]
  },
  {
    province: "Huíla",
    municipalities: [
      "Caconda",
      "Cacula",
      "Caluquembe",
      "Chibia",
      "Chicomba",
      "Chipindo",
      "Cuvango",
      "Gambos",
      "Humpata",
      "Jamba Mineira",
      "Lubango",
      "Matala",
      "Quilengues",
      "Quipungo",
      "Dongo",
      "Hoque",
      "Capelongo",
      "Chitutu",
      "Capunda Cavilongo",
      "Viti Vivali",
      "Galangue",
      "Palanca",
      "Chicungo"
    ],
    municipio:[
{nome:"Caconda", comunas:["Caconda","Gungue","Uaba","Cusse"]},
{nome:"Cacula", comunas:["Cacula","Tchicuaqueia"]},
{nome:"Caluquembe", comunas:["Caluquembe","Calepi","Negola"]},
{nome:"Chibia", comunas:["Chibia","Jau"]},
{nome:"Chicomba", comunas:["Chicomba","Cutenda"]},
{nome:"Chipindo", comunas:["Chipindo","Bambi"]},
{nome:"Cuvango", comunas:[""]},
{nome:"Gambos", comunas:["Chiange","Chimbemba"]},
{nome:"Humpata", comunas:[""]},
{nome:"Jamba Mineira", comunas:["Cassinga","Jamba Mineira"]},
{nome:"Lubango", comunas:["Lubango","Huíla"]},
{nome:"Matala", comunas:[""]},
{nome:"Quilengues", comunas:["Quilengues","Impulo","Dinde"]},
{nome:"Quipungo", comunas:[""]},
{nome:"Dongo", comunas:[""]},
{nome:"Hoque", comunas:[""]},
{nome:"Capelongo", comunas:["Capelongo","Mulondo"]},
{nome:"Chituto", comunas:[""]},
{nome:"Capunda Cavilongo", comunas:["Capunda Cavilongo","Quihita"]},
{nome:"Viti Vivali", comunas:[""]},
{nome:"Galangue", comunas:[""]},
{nome:"Palanca", comunas:[""]},
{nome:"Chicungo", comunas:[""]}
]
  },
  {
    province: "Luanda",
    municipalities: [
"Belas",
"Cacuaco",
"Cazenga",
"Kilamba Kiaxi",
"Viana",
"Mussulo",
"Sambizanga",
"Rangel",
"Maianga",
"Samba",
"Camama",
"Mulenvos",
"Kilamba",
"Hoji Ya Henda",
"Ingombota",
"Talatona"
],
municipio:[
{nome:"Belas", comunas:["Benfica","Cabolombo","Barra do Cuanza","Ramiros"]},
{nome:"Cacuaco", comunas:["Cacuaco","Kikolo"]},
{nome:"Cazenga", comunas:["Cazenga","Kima Kieza"]},
{nome:"Kilamba Kiaxi", comunas:["Golfe","Nova vida"]},
{nome:"Viana", comunas:[""]},
{nome:"Mussulo", comunas:[""]},
{nome:"Sambizanga", comunas:[""]},
{nome:"Rangel", comunas:[""]},
{nome:"Maianga", comunas:[""]},
{nome:"Samba", comunas:[""]},
{nome:"Camama", comunas:[""]},
{nome:"Mulenvos", comunas:[""]},
{nome:"Kilamba", comunas:["Kilamba","Vila Flôr"]},
{nome:"Hoji Ya Henda", comunas:[""]},
{nome:"Ingombota", comunas:[""]},
{nome:"Talatona", comunas:[""]}
]
  },
  {
    province: "Lunda Norte",
    municipalities: [
"Cambulo",
"Capenda Camulemba",
"Caungula",
"Chitato",
"Cuango",
"Cuílo",
"Lubalo",
"Lucapa",
"Lóvua",
"Xá-Muteba",
"Dundo",
"Xá Cassau",
"Camaxilo",
"Luangue",
"Luremo",
"Canzar",
"Cassanje Calucala",
"Mussungue",
"Cafunfo"
],
    municipio:[
{nome:"Cambulo", comunas:["Cachimo","Nzage"]},
{nome:"Capenda Camulemba", comunas:["Capenda Camulemba","Xinge"]},
{nome:"Caungula", comunas:[""]},
{nome:"Chitato", comunas:[""]},
{nome:"Cuango", comunas:[""]},
{nome:"Cuílo", comunas:["Caluango","Cuílo"]},
{nome:"Lubalo", comunas:["Muvuluege","Lubalo"]},
{nome:"Lucapa", comunas:["Camissombo","Lucapa"]},
{nome:"Lóvua", comunas:[""]},
{nome:"Xá-Muteba", comunas:[""]},
{nome:"Dundo", comunas:["Dundo","Luachimo"]},
{nome:"Xá Cassau", comunas:["Xá Cassau","Capaia"]},
{nome:"Camaxilo", comunas:[""]},
{nome:"Luangue", comunas:[""]},
{nome:"Luremo", comunas:[""]},
{nome:"Canzar", comunas:["Canzar","Luia"]},
{nome:"Cassanje Calucala", comunas:["Cassanje Calucala","Iongo"]},
{nome:"Mussungue", comunas:["Mussungue","Caíta"]},
{nome:"Cafunfo", comunas:[""]}
]
  },
  {
    province: "Lunda Sul",
    municipalities: [
"Cacolo",
"Dala",
"Muconda",
"Saurimo",
"Chiluage",
"Cassai-Sul",
"Xassengue",
"Alto Chicapa",
"Sombo",
"Muriege",
"Luma Cassai",
"Cazage",
"Muangueji",
"Cassengo"
],
    municipio:[
{nome:"Cacolo", comunas:[""]},
{nome:"Dala", comunas:[""]},
{nome:"Muconda", comunas:[""]},
{nome:"Saurimo", comunas:["Mona Quimbundo","Saurimo"]},
{nome:"Chiluage", comunas:[""]},
{nome:"Cassai-Sul", comunas:[""]},
{nome:"Xassengue", comunas:["Xassengue","Cucumbi"]},
{nome:"Alto Chicapa", comunas:[""]},
{nome:"Sombo", comunas:[""]},
{nome:"Muriege", comunas:[""]},
{nome:"Luma Cassai", comunas:[""]},
{nome:"Cazage", comunas:[""]},
{nome:"Muangueji", comunas:[""]},
{nome:"Cassengo", comunas:[""]}
]
  },
  {
    province: "Malanje",
    municipalities: [
"Cacuso",
"Cahombo",
"Calandula",
"Cambundi Catembo",
"Cangandala",
"Kiwaba Nzoji",
"Kunda dya Baze",
"Luquembo",
"Malanje",
"Marimba",
"Massango",
"Quela",
"Quirima",
"Cateco Cangola",
"Cuale",
"Pungo a Ndongo",
"Ngola Luiji",
"Quihuhu",
"Xandel",
"Cambo Suingingue",
"Milando",
"Quitapa",
"Capunda",
"Muquixe",
"Quêssua",
"Caculama",
"Mbanji ya Ngola"
],
    municipio:[
{nome:"Cacuso", comunas:["Cacuso","Soqueco"]},
{nome:"Cahombo", comunas:["Micanda","Cahombo"]},
{nome:"Calandula", comunas:["Calandula","Cota"]},
{nome:"Cambundi Catembo", comunas:["Cambundi Catembo","Dumba Cambango"]},
{nome:"Cangandala", comunas:["Cangandala","Caribo","Culamagia"]},
{nome:"Kiwaba Nzoji", comunas:["Kiwaba Nzoji","Mufuma"]},
{nome:"Kunda dya Baze", comunas:["Kunda dya Baze","Lemba"]},
{nome:"Luquembo", comunas:["Luquembo","Dombo wa Zanga"]},
{nome:"Malanje", comunas:["Malanje","Lombe"]},
{nome:"Marimba", comunas:["Marimba","Mangando"]},
{nome:"Massango", comunas:[""]},
{nome:"Quela", comunas:["Quela","Bângalas"]},
{nome:"Quirima", comunas:["Quirima","Sautar"]},
{nome:"Cateco Cangola", comunas:[""]},
{nome:"Cuale", comunas:[""]},
{nome:"Pungo a Ndongo", comunas:[""]},
{nome:"Ngola Luiji", comunas:["Ngola Luiji","Cambaxe"]},
{nome:"Quihugu", comunas:["Quihugu","Quinguengue"]},
{nome:"Xandel", comunas:["Xandel","Moma"]},
{nome:"Cambo Suingingue", comunas:[""]},
{nome:"Milando", comunas:[""]},
{nome:"Quitapa", comunas:[""]},
{nome:"Capunda", comunas:["Capunda","Quimbango","Cunga Palanga"]},
{nome:"Muquixe", comunas:[""]},
{nome:"Quêssua", comunas:[""]},
{nome:"Caculama", comunas:["Caculama","Caxinga"]},
{nome:"Mbanji ya Ngola", comunas:["Mbanji ya Ngola","Cabombo"]}
]
  },
  {
    province: "Moxico",
    municipalities: [
"Chiúme",
"Lumbala Nguimbo",
"Camanongue",
"Léua",
"Alto Cuito",
"Lutembo",
"Cangumbe",
"Luena",
"Cangamba",
"Lucusse",
"Ninda",
"Lutuai"
],
    municipio:[
{nome:"Chiúme", comunas:[""]},
{nome:"Lumbala Nguimbo", comunas:["Lumbala Nguimbo","Mussuma Mitete","Sessa"]},
{nome:"Camanongue", comunas:[""]},
{nome:"Léua", comunas:["Léua","Liangongo"]},
{nome:"Alto Cuito", comunas:[""]},
{nome:"Lutembo", comunas:["Lutembo","Luvuei"]},
{nome:"Cangumbe", comunas:[""]},
{nome:"Luena", comunas:["Luena","Cassongo"]},
{nome:"Cangamba", comunas:["Cangombe","Cassamba","Cangamba","Muié"]},
{nome:"Lucusse", comunas:[""]},
{nome:"Ninda", comunas:[""]},
{nome:"Lutuai", comunas:[""]}
]
  },
  {
    province: "Namibe",
    municipalities: [
"Moçâmedes",
"Camucuio",
"Bibala",
"Virei",
"Tômbua",
"Lucira",
"Iona",
"Sacomar",
"Cacimbas"
],
    municipio:[
{nome:"Moçâmedes", comunas:[""]},
{nome:"Camucuio", comunas:["Camucuio","Mamué","Chingo"]},
{nome:"Bibala", comunas:["Bibala","Capangombe","Caitou","Lola"]},
{nome:"Virei", comunas:["Virei","Cainde"]},
{nome:"Tômbua", comunas:[""]},
{nome:"Lucira", comunas:["Lucira","Bentiaba"]},
{nome:"Iona", comunas:[""]},
{nome:"Sacomar", comunas:[""]},
{nome:"Cacimbas", comunas:[""]}
]
  },
  {
    province: "Uíge",
    municipalities:[
  "Uíge",
  "Cangola",
  "Ambuíla",
  "Bembe",
  "Nova Esperança",
  "Bungo",
  "Milunga",
  "Damba",
  "Maquela do Zombo",
  "Mucaba",
  "Negage",
  "Puri",
  "Quimbele",
  "Dange Quitexe",
  "Sanza Pombo",
  "Songo",
  "Sacandica",
  "Nsosso",
  "Lucunga",
  "Quipedro",
  "Massau",
  "Vista Alegre",
  "Alto Zaza"
],
    municipio:[
{nome:"Uíge", comunas:["Uíge","Luanga","Casseche","Cancungo"]},
{nome:"Cangola", comunas:["Cangola","Bengo","Caiongo"]},
{nome:"Ambuíla", comunas:[""]},
{nome:"Bembe", comunas:["Bembe","Mabaia"]},
{nome:"Nova Esperança", comunas:["Nova Esperança","Buenga - Sul","Cuilo Camboso"]},
{nome:"Bungo", comunas:[""]},
{nome:"Milunga", comunas:["Milunga","Macocola"]},
{nome:"Damba", comunas:["Damba","Petecusso","Camatambo","Lêmboa"]},
{nome:"Maquela do Zombo", comunas:["Maquela do Zombo","Quibocolo"]},
{nome:"Mucaba", comunas:["Mucaba","Uando Mucaba"]},
{nome:"Negage", comunas:["Negage","Dimuca","Quisseque"]},
{nome:"Puri", comunas:[""]},
{nome:"Quimbele", comunas:["Quimbele","Icoca"]},
{nome:"Dange Quitexe", comunas:["Quitexe","Aldeia Viçosa"]},
{nome:"Sanza Pombo", comunas:["Sanza Pombo","Cuilo Pombo","Uamba","Alfândega"]},
{nome:"Songo", comunas:["Songo","Quivuenga"]},
{nome:"Sacandica", comunas:["Sacandica","Cuilo Futa","Béu"]},
{nome:"Nsosso", comunas:[""]},
{nome:"Lucunga", comunas:[""]},
{nome:"Quipedro", comunas:[""]},
{nome:"Massau", comunas:["Massau","Macolo"]},
{nome:"Vista Alegre", comunas:["Vista Alegre","Cambamba"]},
{nome:"Alto Zaza", comunas:["Alto Zaza","Cuango Calumbo"]}
]
  },
  {
    province: "Zaire",
    municipalities: [
"Mbanza Kongo",
"Soyo",
"Nzeto",
"Cuimba",
"Nóqui",
"Tomboco",
"Luvo",
"Lufico",
"Quêlo",
"Serra de Canda",
"Quindeje"
],
    municipio: [
{nome:"Mbanza Kongo", comunas:["Mbanza Kongo","Caluca","Madimba","Quiende"]},
{nome:"Soyo", comunas:["Soyo","Pedra de Feitiço"]},
{nome:"Nzeto", comunas:["Nzeto","Musserra","Quibala Norte"]},
{nome:"Cuimba", comunas:["Cuimba","Buela","Luvaca"]},
{nome:"Nóqui", comunas:["Mpala"]},
{nome:"Tomboco", comunas:["Tomboco","Quinsimba","Quinzau"]},
{nome:"Luvo", comunas:[""]},
{nome:"Lufico", comunas:["Lufico"]},
{nome:"Quêlo", comunas:[""]},
{nome:"Serra de Canda", comunas:[""]},
{nome:"Quindeje", comunas:["Quibala - Norte","Quindeje"]}
]
  },
  {
    province: "Icolo e Bengo",
    municipalities: [
"Catete",
"Quiçama",
"Calumbo",
"Cabiri",
"Cabo Ledo",
"Bom Jesus",
"Sequele"
],
    municipio:[
{nome:"Catete", comunas:["Catete","Cassoneca","Caculo Cahango","Caxicane"]},
{nome:"Quiçama", comunas:["Muxima","Quixinge","Demba Chio","Mumbondo"]},
{nome:"Calumbo", comunas:[""]},
{nome:"Cabiri", comunas:[""]},
{nome:"Cabo Ledo", comunas:[""]},
{nome:"Bom Jesus", comunas:[""]},
{nome:"Sequele", comunas:["Funda","Quifangondo","Sequele"]}
]
  },
  {
    province: "Moxico Leste",
    municipalities: [
"Cazombo",
"Luacano",
"Cameia",
"Luau",
"Nana Candundo",
"Macondo",
"Caianda",
"Lóvua do Zambeze",
"Lago Dilolo"
],
    municipio:[
{nome:"Cazombo", comunas:["Cazombo","Lumbala Caquengue"]},
{nome:"Luacano", comunas:[""]},
{nome:"Cameia", comunas:[""]},
{nome:"Luau", comunas:[""]},
{nome:"Nana Candundo", comunas:[""]},
{nome:"Macondo", comunas:["Macondo","Calunda"]},
{nome:"Caianda", comunas:[""]},
{nome:"Lóvua do Zambeze", comunas:[""]},
{nome:"Lago Dilolo", comunas:[""]}
]
  },
  {
    province: "Cuando",
    municipalities:[
"Cuito Cuanavale",
"Dirico",
"Mavinga",
"Rivungo",
"Xipundo",
"Dima",
"Luiana",
"Mucusso",
"Luengue"
],
municipio:[
{nome:"Cuito Cuanavale", comunas:["Cuito Cuanavale","Lupire"]},
{nome:"Dirico", comunas:["Dirico","Xamavera"]},
{nome:"Mavinga", comunas:[""]},
{nome:"Rivungo", comunas:[""]},
{nome:"Xipundo", comunas:[""]},
{nome:"Dima", comunas:["Cunjamba","Cutuile"]},
{nome:"Luiana", comunas:[""]},
{nome:"Mucusso", comunas:[""]},
{nome:"Luengue", comunas:[""]}
]
  },
  ,
  {
    province: "Cubango",
    municipalities: [
"Calai",
"Cuangar",
"Cuchi",
"Cutato",
"Caiundo",
"Longa",
"Menongue",
"Nancova",
"Savate",
"Chinguar",
"Mavengue"
],
municipio:[
{nome:"Calai", comunas:[""]},
{nome:"Cuangar", comunas:[""]},
{nome:"Cuchi", comunas:[""]},
{nome:"Cutato", comunas:["Cutato","Vissati"]},
{nome:"Caiundo", comunas:["Caiundo","Jamba Cueio"]},
{nome:"Longa", comunas:["Longa","Baixo Longa"]},
{nome:"Menongue", comunas:[""]},
{nome:"Nancova", comunas:["Nancova","Rito"]},
{nome:"Savate", comunas:["Savate","Bondo Caíla"]},
{nome:"Chinguar", comunas:[""]},
{nome:"Mavengue", comunas:["Mavengue","Maué"]}
]
  }
]